Update class-photonfill.php
Fixes fatal error which was breaking things in the admin, and possibly elsewhere; 

`
Fatal error: [] operator not supported for strings in /var/www/mason/wordpress-trunk/wp-content/plugins/photonfill-master/php/class-photonfill.php on line 523
`